<a href="https://colab.research.google.com/github/Avani80/foundations-of-ML/blob/main/cse273.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2 = np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr3 = np.arange(1,11,2)
arr3

array([1, 3, 5, 7, 9])

In [ ]:
arr4 = np.zeros(6)
arr4

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr5 = np.ones(6)
arr5

array([1., 1., 1., 1., 1., 1.])

In [ ]:
arr6 = np.linspace(1,10,3)
arr6

array([ 1. ,  5.5, 10. ])

In [ ]:
#random generation function , numbers coming bw 0 to 1 means normalization
ar1 = np.random.rand(2)
ar1

array([0.53968262, 0.79163959])

In [ ]:
#number coming bw -3 to 3 means standardization
ar2 = np.random.randn(3)
ar2

array([ 1.03353207, -0.19539595, -0.90514433])

In [ ]:
#array attributes
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape


(3, 3)

In [ ]:
a.size

9

In [ ]:
a.dtype

dtype('int64')

In [ ]:
#array methods
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(4)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis = 0) #sum of column , for rows axis = 1

array([12, 15, 18])

In [ ]:
#reshaping and reshizing
ara = np.arange(1,26)
ara

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
ara.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#indexing and slicing
n = np.arange(1,31).reshape(6,5)
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
n[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [7]:
import numpy as np
arr = np.arange(11,21)
bool_index = arr%2 == 0
print(bool_index)
arr = arr[bool_index]
print(arr)

[False  True False  True False  True False  True False  True]
[12 14 16 18 20]


In [8]:
#numpy or array operation arithmetic operation
a1 = np.array([1 ,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1+a2


array([ 7,  9, 11, 13, 15])

In [9]:
# broadcasting
l = [10 , 20 , 30 ,40]
arr = np.array(l)
arr+10

array([20, 30, 40, 50])

In [13]:
# deep and shallow copy
b1 = np.arange(1 ,20)
slice = b1[:5]
slice


array([1, 2, 3, 4, 5])

In [14]:
slice = slice * 10
print(slice) # shallow copy means what we changes do on slice part , no effect main array , main array mai koi chng nhi hoga

[10 20 30 40 50]


In [16]:
# matrix operation
#1 multiply
A = np.array([[1 ,2],[3,4]])
B = np.array([[5,6],[7,8]])
A@B # np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [17]:
#transpose
A.T

array([[1, 3],
       [2, 4]])

In [18]:
#Advance array manipulation
#1 stacking array u can not stack 2 array or matrix
a = np.array([1,2,3,4])
b = np.array([5 ,6,7,8])
np.vstack((a,b)) # np.hstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
# splitting array
c = np.arange(16).reshape(4,4)
np.hsplit(c,2) # horitzontal split


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [20]:
np.vsplit(c,2) # vertical split

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
#pandas  class
import pandas as pd
import numpy as np
data  = {'First Score' : [100 , 90 , np.nan,95],'Seccond Score':[30,45,56,np.nan],'Third Score' : [np.nan,40,80,98]}
df = pd.DataFrame(data)# covert this data into tabular format
#missing_values = df.isnull()
missing_values = df.notnull()
print(missing_values)

   First Score  Seccond Score  Third Score
0         True           True        False
1         True           True         True
2        False           True         True
3         True          False         True


In [ ]:
import pandas as pd # selecting of data
data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Arjun", "Meera", "Karan", "Pooja"],
    "Age": [17, 18, 17, 19, 18, 17, 19, 18],
    "City": ["Delhi", "Mumbai", "Delhi", "Chennai", "Kolkata", "Mumbai", "Chennai", "Delhi"],
    "Marks": [85, 92, 76, 88, 95, 67, 73, 90] }
df = pd.DataFrame(data)
print("complete Dataset:")
print(df)


complete Dataset:
   Student_ID   Name  Age     City  Marks
0         101   Amit   17    Delhi     85
1         102  Priya   18   Mumbai     92
2         103  Rahul   17    Delhi     76
3         104  Sneha   19  Chennai     88
4         105  Arjun   18  Kolkata     95
5         106  Meera   17   Mumbai     67
6         107  Karan   19  Chennai     73
7         108  Pooja   18    Delhi     90


In [ ]:
print(df["Name"])
print(df[["Name","Marks"]])#select multiple columns

0     Amit
1    Priya
2    Rahul
3    Sneha
4    Arjun
5    Meera
6    Karan
7    Pooja
Name: Name, dtype: object
    Name  Marks
0   Amit     85
1  Priya     92
2  Rahul     76
3  Sneha     88
4  Arjun     95
5  Meera     67
6  Karan     73
7  Pooja     90


In [ ]:
print(df.iloc[0]) # 1 row

Student_ID      101
Name           Amit
Age              17
City          Delhi
Marks            85
Name: 0, dtype: object


In [ ]:
print(df.iloc[:3])

   Student_ID   Name  Age    City  Marks
0         101   Amit   17   Delhi     85
1         102  Priya   18  Mumbai     92
2         103  Rahul   17   Delhi     76


In [ ]:
#specific row and column(row 2,column 3)
print(df.iloc[2,3])

Delhi


In [ ]:
print(df.loc[4]) # iloc is by default integer

Student_ID        105
Name            Arjun
Age                18
City          Kolkata
Marks              95
Name: 4, dtype: object


In [ ]:
#filtering of data
print(df[df["Marks"] > 85]) # df 2 times 1 for whole data 2 nd for

   Student_ID   Name  Age     City  Marks
1         102  Priya   18   Mumbai     92
3         104  Sneha   19  Chennai     88
4         105  Arjun   18  Kolkata     95
7         108  Pooja   18    Delhi     90


In [ ]:
print(df[(df["Marks"]>80) & (df["Age"] < 19)])

   Student_ID   Name  Age     City  Marks
0         101   Amit   17    Delhi     85
1         102  Priya   18   Mumbai     92
4         105  Arjun   18  Kolkata     95
7         108  Pooja   18    Delhi     90


In [ ]:
print(df[(df["City"]== "Delhi") | (df["City"] == "Mumbai")])

   Student_ID   Name  Age    City  Marks
0         101   Amit   17   Delhi     85
1         102  Priya   18  Mumbai     92
2         103  Rahul   17   Delhi     76
5         106  Meera   17  Mumbai     67
7         108  Pooja   18   Delhi     90
