<a href="https://colab.research.google.com/github/Avani80/foundations-of-ML/blob/main/cse273.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2 = np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr3 = np.arange(1,11,2)
arr3

array([1, 3, 5, 7, 9])

In [ ]:
arr4 = np.zeros(6)
arr4

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr5 = np.ones(6)
arr5

array([1., 1., 1., 1., 1., 1.])

In [ ]:
arr6 = np.linspace(1,10,3)
arr6

array([ 1. ,  5.5, 10. ])

In [ ]:
#random generation function , numbers coming bw 0 to 1 means normalization
ar1 = np.random.rand(2)
ar1

array([0.53968262, 0.79163959])

In [ ]:
#number coming bw -3 to 3 means standardization
ar2 = np.random.randn(3)
ar2

array([ 1.03353207, -0.19539595, -0.90514433])

In [ ]:
#array attributes
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape


(3, 3)

In [ ]:
a.size

9

In [ ]:
a.dtype

dtype('int64')

In [ ]:
#array methods
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(4)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis = 0) #sum of column , for rows axis = 1

array([12, 15, 18])

In [ ]:
#reshaping and reshizing
ara = np.arange(1,26)
ara

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
ara.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#indexing and slicing
n = np.arange(1,31).reshape(6,5)
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
n[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [3]:
#pandas  class
import pandas as pd
import numpy as np
data  = {'First Score' : [100 , 90 , np.nan,95],'Seccond Score':[30,45,56,np.nan],'Third Score' : [np.nan,40,80,98]}
df = pd.DataFrame(data)# covert this data into tabular format
#missing_values = df.isnull()
missing_values = df.notnull()
print(missing_values)

   First Score  Seccond Score  Third Score
0         True           True        False
1         True           True         True
2        False           True         True
3         True          False         True


In [10]:
import pandas as pd
data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Arjun", "Meera", "Karan", "Pooja"],
    "Age": [17, 18, 17, 19, 18, 17, 19, 18],
    "City": ["Delhi", "Mumbai", "Delhi", "Chennai", "Kolkata", "Mumbai", "Chennai", "Delhi"],
    "Marks": [85, 92, 76, 88, 95, 67, 73, 90] }
df = pd.DataFrame(data)
print("complete Dataset:")
print(df)


complete Dataset:
   Student_ID   Name  Age     City  Marks
0         101   Amit   17    Delhi     85
1         102  Priya   18   Mumbai     92
2         103  Rahul   17    Delhi     76
3         104  Sneha   19  Chennai     88
4         105  Arjun   18  Kolkata     95
5         106  Meera   17   Mumbai     67
6         107  Karan   19  Chennai     73
7         108  Pooja   18    Delhi     90


In [11]:
print(df["Name"])
print(df[["Name","Marks"]])#select multiple columns

0     Amit
1    Priya
2    Rahul
3    Sneha
4    Arjun
5    Meera
6    Karan
7    Pooja
Name: Name, dtype: object
    Name  Marks
0   Amit     85
1  Priya     92
2  Rahul     76
3  Sneha     88
4  Arjun     95
5  Meera     67
6  Karan     73
7  Pooja     90


In [12]:
print(df.iloc[0]) # 1 row

Student_ID      101
Name           Amit
Age              17
City          Delhi
Marks            85
Name: 0, dtype: object


In [13]:
print(df.iloc[:3])

   Student_ID   Name  Age    City  Marks
0         101   Amit   17   Delhi     85
1         102  Priya   18  Mumbai     92
2         103  Rahul   17   Delhi     76


In [14]:
#specific row and column(row 2,column 3)
print(df.iloc[2,3])

Delhi
