<a href="https://colab.research.google.com/github/Avani80/foundations-of-ML/blob/main/exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#check this is valid sudoku or not
s = np.array([
    [5,3,0,0,7,0,0,0,0],
    [6,0,0,1,9,5,0,0,0],
    [0,9,8,0,0,0,0,6,0],
    [8,0,0,0,6,0,0,0,3],
    [4,0,0,8,0,3,0,0,1],
    [7,0,0,0,2,0,0,0,6],
    [0,6,0,0,0,0,2,8,0],
    [0,0,0,4,1,9,0,0,5],
    [0,0,0,0,8,0,0,7,9]
])

In [ ]:
#check this is valid sudoku or not
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],
    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],
    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

b = np.sum(s,axis = 1) # sum of rows
b == 45


array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [ ]:
b = np.sum(s,axis = 1)
for i in b:
  if i != 45:
    print("sudoku is not valid")
    break
else:
  print("for rows it is valid")

for rows it is valid


In [ ]:
import numpy as np
# columns : [age,math  marks , science marks]
data = np.array([
 [18,85,78],
 [19,92,88],
 [17,76,95],
 [18,65,70],
 [20,90,85]
])
data.shape #get the shape of the matrix

(5, 3)

In [ ]:
# find the average age of the students
np.mean(data[:,0])

np.float64(18.4)

In [ ]:
#extract math marks of all students
data[:,1]

array([85, 92, 76, 65, 90])

In [ ]:
#find teh highest science max
np.max(data[:,2])

np.int64(95)

In [ ]:
# get details of the student who scored more then 90 maths
data[data[:,1] > 90]

array([[19, 92, 88]])

In [ ]:
#increase maths marks of all students by 5
data[:,1] = data[:,1]+5
data

array([[ 23, 110,  83],
       [ 19, 112,  88],
       [ 17,  96,  95],
       [ 18,  85,  70],
       [ 20, 110,  85]])

In [ ]:
#calculate the average of marks in each subject column wise
data.mean(axis=0)

array([ 19.4, 102.6,  84.2])

In [ ]:
#replace all science marks < 75  with 0
data[data[:,2] < 75,2] = 0
data

array([[ 23, 110,  83],
       [ 19, 112,  88],
       [ 17,  96,  95],
       [ 18,  85,   0],
       [ 20, 110,  85]])

In [ ]:
# get data of students who scored at least 80 in both subjects
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[ 23, 110,  83],
       [ 19, 112,  88],
       [ 17,  96,  95],
       [ 20, 110,  85]])